### ISSUE TITLE
[MQTTSession error] when iam switching between the chatrooms

### ISSUE THREAD

**Issue by MuralikrishnaM** [ibm-messaging/mqtt-ios-sample#1]
Hi Iam Murali
I am using this sample code for developing the chat application for ios platform. 
Iam making a connection to server in the viewDidLoad of the page. First time when iam loading the chatroom, its working fine, but as soon as i click back on the page, and select another room, and entering into the room, iam encounntering the [MQTTSession error]. Please suggest, how to resolve this issue. Thank you somuch for your time on this

**Comment by MuralikrishnaM** [comment]
I did not even get a clue, on how to disconnect the device in this library, please suggest this as well

**Comment by robert17** [comment]
What MQTT library are you using? MQTTSession doesn't look like its from the same library that this sample was originally written with.

**Comment by MuralikrishnaM** [comment]
hi Thanks for your quick responce. I am using this library. I have uploaded the screen shot for your reference. Thank you so much for your time on this
<img width="1083" alt="screen shot 2016-03-31 at 12 26 23 am" src="https://cloud.githubusercontent.com/assets/2756187/14149565/5a971278-f6d7-11e5-80be-23284cd49d36.png">

**Comment by MuralikrishnaM** [comment]
Please excuse me. You are correct. Can you please ignore my comments.
